// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Sortable from 'stimulus-sortable'

import IngredientsPanelController from "./recipes/ingredients_panel"
import NestedAssociationsController from "./nested_associations_controller"
import SmartRecipeFormController from "./smart_recipe_form_controller"
import SmartSelectController from "./smart_select"
import ToastsController from "./toasts"

application.register("smart-recipe-form", SmartRecipeFormController)
application.register("toasts", ToastsController)
application.register("nested-associations", NestedAssociationsController)
application.register("ingredients-panel", IngredientsPanelController)
application.register("smart-select", SmartSelectController)
application.register("sortable", Sortable)
