// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { SmartRecipeFormController } from "./smart_recipe_form_controller"
import { ToastsController } from "./toasts"

application.register("smart-recipe-form", SmartRecipeFormController)
application.register("toasts", ToastsController)
