// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Sortable from 'stimulus-sortable'

import IngredientsPanelController from "./recipes/ingredients_panel_controller"
import NestedAssociationsController from "./nested_associations_controller"
import SmartRecipeFormController from "./smart_recipe_form_controller"
import SmartSelectController from "./smart_select_controller"
import ToastsController from "./toasts_controller"
import ImagePreviewController from "./image_preview_controller"
import InfiniteScrollingController from "./infinite_scrolling_controller"
import StickyController from "./sticky_controller"

application.register("smart-recipe-form", SmartRecipeFormController)
application.register("toasts", ToastsController)
application.register("nested-associations", NestedAssociationsController)
application.register("ingredients-panel", IngredientsPanelController)
application.register("smart-select", SmartSelectController)
application.register("sortable", Sortable)
application.register("sticky", StickyController)
application.register("image-preview", ImagePreviewController)
application.register("infinite-scrolling", InfiniteScrollingController)
