test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google: &google_storage
  service: GCS
  private_key_id: <%= ENV.fetch('STORAGE_ACCESS_KEY_ID', 'CLOUD_STORAGE_KEY_ID') %>
  private_key: <%= ENV.fetch('STORAGE_SECRET_ACCESS_KEY', 'CLOUD_STORAGE_SECRET_ACCESS_KEY') %>
  project: <%= ENV.fetch('STORAGE_PROJECT_ID', 'cookpendium') %>
  bucket: <%= ENV.fetch('STORAGE_BUCKET_NAME', 'cookpendium') %>
  <% if ENV.key?('STORAGE_ENDPOINT_URL') %>
  endpoint: <%= ENV.fetch('STORAGE_ENDPOINT_URL') %>
  force_path_style: true
  <% end %>