test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google: &google_storage
  service: GCS
  credentials: <%= Rails.root.join("config/external_credentials/google_cloud_storage.json") %>
  project: <%= ENV.fetch('STORAGE_PROJECT_ID', 'cookpendium') %>
  bucket: <%= ENV.fetch('STORAGE_BUCKET_NAME', 'cookpendium') %>
