name: RSpec Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip specs]')"
    steps:
      - uses: actions/checkout@v5
      - name: BUILD TEST
        run: docker-compose build test
      - name: MIGRATE TEST
        run: docker-compose run test rails db:create db:migrate
      - name: RUN RSPEC
        run: docker-compose run test rspec
