name: RSpec Tests

on:
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Change this to your Ruby version

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RSpec Tests
        run: bundle exec rspec
